### ISSUE TITLE
Fix Demand-Based Mod Loading

### ISSUE THREAD

**Issue by siky112** [samfundev/KTANE-Mods#23]
Yes, I am bestga.

I decided to enable the Demand-Based Mod Loading setting and it doesn't work, the mods just load the same as normal.

Here are the settings I'm using:
`{
  "FadeTime": 1.0,
  "InstantSkip": true,
  "SkipGameplayDelay": false,
  "BetterCasePicker": false,
  "EnableModsOnlyKey": false,
  "DemandBasedModLoading": true,
  "DemandBasedModsExcludeList": [],
  "DemandModLimit": -1,
  "FixFER": false,
  "BombHUD": false,
  "ShowEdgework": true,
  "DisableAdvantageous": true,
  "ShowTips": true,
  "HideTOC": [],
  "Mode": "Zen",
  "MissionSeed": -1,
  "CaseGenerator": true,
  "ModuleTweaks": true,
  "CaseColors": [
"random"
],
  "Holdables": {
    "FreeplayDevice": true,
    "BombBinder": true,
    "ModManager": true,
    "DossierMenu": true,
    "BombCreator": true,
    "ModSelectorTablet": true
  },
  "PinnedSettings": []
}`

**Comment by samfundev** [comment]
My apologies, I never thought about contacting someone on GitHub. As for your issue, your settings look correct to me.

Just to be clear, Demand-Based Mod Loading only applies to modules. It cannot load gameplay rooms, bomb cases, services, etc. on demand. Can you confirm that the game loaded up a bunch of modules when the game first loaded up instead of just loading things like gameplay rooms? And this happened even after you restarted the game?

If you can confirm that's the case, then please give me a logfile after you load into the game with this bug happening. On Windows, the logfile is located at `%APPDATA%\..\LocalLow\Steel Crate Games\Keep Talking and Nobody Explodes\output_log.txt`. I can give you the paths for the other OSes if you're not on Windows.

**Comment by siky112** [comment]
It is loading modules, not just other stuff. It's still going very slow, too. Will give you a log once the game fully loads.

**Comment by siky112** [comment]
the game froze in the loading screen between the mod loading screen and the setup room so i will have to load it all again

**Comment by siky112** [comment]
nevermind it worked

**Comment by siky112** [comment]
It did not work, it only disabled a bunch of stuff. I also loaded a random bomb and can confirm it is broken. I have also included the output log.
[output_log.txt](https://github.com/samfundev/KTANE-Mods/files/5496573/output_log.txt)

**Comment by siky112** [comment]
wait i just have it wrong it only works after you load up the game once
